version: "3.9"

services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    env_file:
      - .env

  web:
    build: .
    command: /code/wait-for-it.sh db:5432 -- ./docker-entrypoint.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
