# Generated by Django 5.0.6 on 2024-06-01 11:45

import django.db.models.deletion
import hero_crafter.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                    ),
                ),
                ("strength", hero_crafter.models._AbilityScoreField()),
                ("intelligence", hero_crafter.models._AbilityScoreField()),
                ("wisdom", hero_crafter.models._AbilityScoreField()),
                ("dexterity", hero_crafter.models._AbilityScoreField()),
                ("constitution", hero_crafter.models._AbilityScoreField()),
                ("charisma", hero_crafter.models._AbilityScoreField()),
                ("hit_points", models.IntegerField()),
                (
                    "race",
                    models.CharField(
                        choices=[
                            ("D", "Dwarf"),
                            ("E", "Elf"),
                            ("HL", "Halfling"),
                            ("H", "Human"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "character_class",
                    models.CharField(
                        choices=[
                            ("C", "Cleric"),
                            ("F", "Fighter"),
                            ("M", "Mage"),
                            ("T", "Thief"),
                        ],
                        db_column="class",
                        max_length=1,
                    ),
                ),
                (
                    "alignment",
                    models.CharField(
                        choices=[
                            ("LG", "Lawful Good"),
                            ("NG", "Neutral Good"),
                            ("CG", "Chaotic Good"),
                            ("LN", "Lawful Neutral"),
                            ("TN", "True Neutral"),
                            ("CN", "Chaotic Neutral"),
                            ("LE", "Lawful Evil"),
                            ("NE", "Neutral Evil"),
                            ("CE", "Chaotic Evil"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="characters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
