# Generated by Django 5.0.6 on 2024-06-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hero_crafter", "0002_character_biography"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="portrait_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
